# Generated by Django 5.2.17 on 2026-09-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
